export const SAMPLE_MAPS = [
  {
    id: 1,
    name: "8 Doors",
    author: "POOLED",
    gamemodes: ["normal"],
    image: "8-doors.svg",
    difficulty: "●○○○",
    players: "1-2",
  },
  {
    id: 2,
    name: "8 Gaps",
    author: "POOLED",
    gamemodes: ["normal"],
    image: "8-gaps.svg",
    difficulty: "●○○○",
    players: "1-2",
  },
  {
    id: 3,
    name: "Tunnel",
    author: "POOLED",
    gamemodes: ["normal"],
    image: "tunnel.svg",
    difficulty: "●●○○",
    players: "1-2",
  },
  {
    id: 4,
    name: "Roundabout",
    author: "POOLED",
    gamemodes: ["normal", "freeze"],
    image: "roundabout.svg",
    difficulty: "●○○○",
    players: "1",
  },
  {
    id: 5,
    name: "Big One",
    author: "POOLED",
    gamemodes: ["normal", "freeze"],
    image: "big-one.svg",
    difficulty: "●●○○",
    players: "2",
  },
  {
    id: 6,
    name: "Big One 2",
    author: "POOLED",
    gamemodes: ["normal", "freeze"],
    image: "big-one-2.svg",
    difficulty: "●●○○",
    players: "2",
  },
];
